### ISSUE TITLE
Aubio encoder fails on particular stream coming from youtube

### ISSUE THREAD

**Issue by yomguy** [Parisson/TimeSide#290]
For example, retrieving the audio stream of this video with youtube-dl:

https://www.youtube.com/watch?v=04854XqcfCY

results to this:

https://timeside.ircam.fr/media/items/download/Queen_-_We_Are_The_Champions_Official_Video-04854XqcfCY.m4a

and encoding it to FLAC with timeside returns: 

```
[2022-07-05 10:10:35,435: INFO/ForkPoolWorker-14] timeside.server.tasks.experience_run[2f60ffe0-d989-4a91-b844-e7dbab116a45]: Run flac_aubio_encoder-{} on Queen - We are the champions_00af                     
2022-07-05 10:10:35,435 - 2f60ffe0-d989-4a91-b844-e7dbab116a45 - timeside.server.tasks.experience_run - timeside.server.models - INFO - Run flac_aubio_encoder-{} on Queen - We are the champions_00af           
[2022-07-05 10:10:35,435: WARNING/ForkPoolWorker-14] setting up aubio with with
[2022-07-05 10:10:35,435: WARNING/ForkPoolWorker-14] 44100
[2022-07-05 10:10:35,436: WARNING/ForkPoolWorker-14] 8192
[2022-07-05 10:10:36,470: ERROR/ForkPoolWorker-14] Task timeside.server.tasks.experience_run[2f60ffe0-d989-4a91-b844-e7dbab116a45] raised unexpected: ValueError('input array dimension 1 should be greater than 0
')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/lib/timeside/timeside/server/tasks.py", line 130, in experience_run
    raise e
  File "/srv/lib/timeside/timeside/server/tasks.py", line 111, in experience_run
    item.run(experience, task=task, item=item)
  File "/srv/lib/timeside/timeside/server/models.py", line 628, in run
    pipe.run()
  File "/srv/lib/timeside/timeside/core/processor.py", line 562, in run
    eod
  File "/srv/lib/timeside/timeside/core/aubio_encoder.py", line 81, in process
    self.sink.do_multi(f_slice.T.copy(), write_frames)
ValueError: input array dimension 1 should be greater than 0
```

**Comment by yomguy** [comment]
thanks @piem could you commit this?
