### ISSUE TITLE
TimeSide OS X

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#77]
Hi,

I'm trying (again) to use TimeSide on os x, without Docker. I have the following error : 
```
>>> import timeside
>>> from timeside.core.tools.test_samples import samples
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "timeside/core/__init__.py", line 41, in <module>
    _WITH_VAMP = ts_package.check_vamp()
  File "timeside/core/tools/package.py", line 119, in check_vamp
    from timeside.plugins.analyzer.externals import vamp_plugin
  File "timeside/plugins/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2167, in declare_namespac
e
    declare_namespace(parent)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2183, in declare_namespac
e
    _handle_ns(packageName, path_item)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2150, in _handle_ns
    loader.load_module(packageName)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py"
, line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/local/lib/python2.7/site-packages/timeside/__init__.py", line 25, in <module>
    from . import core
ImportError: cannot import name core
>>> 
```

**Comment by yomguy** [comment]
Hi Anas,
From TimeSide 0.7, you should import the module with:
```import timeside.core```
Sory if the doc is not completely up to date with this yet...

**Comment by AnasGhrab** [comment]
```
>>> import timeside.core
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl
.py", line 429, in new_import
    fromlist=fromlist, level=level)
  File "timeside/core/__init__.py", line 41, in <module>
    _WITH_VAMP = ts_package.check_vamp()
  File "timeside/core/tools/package.py", line 119, in check_vamp
    from timeside.plugins.analyzer.externals import vamp_plugin
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl
.py", line 429, in new_import
    fromlist=fromlist, level=level)
  File "timeside/plugins/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", l
ine 2193, in declare_namespace
    declare_namespace(parent)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", l
ine 2209, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", l
ine 2176, in _handle_ns
    loader.load_module(packageName)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/timeside/__init__.py", line 2
6, in <module>
    from . import core
ImportError: cannot import name core
```

It works with ```import timeside```

**Comment by AnasGhrab** [comment]
The install of TimeSide works now for me. I have these installed using homebrew : 
```
homebrew/versions/gst-plugins-bad010 (installed)
homebrew/versions/gst-plugins-base010 (installed)
homebrew/versions/gst-plugins-good010 (installed)
gst-plugins-base (installed)
homebrew/versions/gst-plugins-ugly010 (installed)
homebrew/versions/gst-python010 (installed)
gst-python (installed)
homebrew/versions/gstreamer010 (installed)
gstreamer (installed)
```

and set the $PYTHONPATH because the paths of pygst.py and pygtk.py are not reached.

**Comment by yomguy** [comment]
Really good news!! Congrats and thanks for the info, Anas
I hope to be able to install 0.8 well through docker this week.
