### ISSUE TITLE
Gstreamer : TLS/SSL support not available

### ISSUE THREAD

**Issue by thomasfillon** [Parisson/TimeSide#94]
It seems that Conda Glib library does not provide glib-networking , the network-related giomodules for GLib.

> Traceback (most recent call last):
>   File "tests/test_decoder_utils.py", line 98, in tearDown
>     uri_info = get_media_uri_info(uri)
>   File "/srv/src/timeside/timeside/plugins/decoder/utils.py", line 133, in get_media_uri_info
>     raise IOError(e)
> IOError: TLS/SSL support not available; install glib-networking
> 

The bug seems to have appeared with some upgrade of Conda version.

**Comment by thomasfillon** [comment]
Temporary fix by linking miniconda libgio library to system libgio in a2bc1f55f72a .
